import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&family=Open+Sans:wght@300;400;600;700;800&family=Lato:wght@300;400;700;900&family=Montserrat:wght@300;400;500;600;700;800;900&family=Oswald:wght@300;400;500;600;700&family=Raleway:wght@300;400;500;600;700;800;900&family=Poppins:wght@300;400;500;600;700;800;900&family=Merriweather:wght@300;400;700;900&family=Playfair+Display:wght@400;500;600;700;800;900&family=Ubuntu:wght@300;400;500;700&family=Noto+Sans:wght@400;700&family=Bebas+Neue&family=Dancing+Script:wght@400;500;600;700&family=Pacifico&family=Lobster&family=Righteous&family=Anton&family=Archivo+Black&family=Satisfy&family=Permanent+Marker&family=Indie+Flower&family=Caveat:wght@400;500;600;700&family=Shadows+Into+Light&family=Bangers&family=Press+Start+2P&family=Rubik:wght@300;400;500;600;700;800;900&family=Nunito:wght@300;400;600;700;800;900&family=Quicksand:wght@300;400;500;600;700&family=Source+Sans+3:wght@300;400;600;700;900&family=Comfortaa:wght@300;400;500;600;700&family=Yanone+Kaffeesatz:wght@300;400;500;600;700&family=PT+Sans:wght@400;700&family=Josefin+Sans:wght@300;400;600;700&family=Cinzel:wght@400;600;700;900&family=Great+Vibes&family=Amatic+SC:wght@400;700&family=Bungee&family=Barlow:wght@300;400;500;600;700;800;900&family=Bitter:wght@300;400;500;600;700;800;900&family=Alfa+Slab+One&family=Orbitron:wght@400;500;600;700;800;900&family=Russo+One&family=Teko:wght@300;400;500;600;700&family=Fredoka:wght@300;400;500;600;700&family=Concert+One&family=Signika:wght@300;400;500;600;700&family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
